### ISSUE TITLE
Railsの環境構築

### ISSUE THREAD

**Issue by kazumi3858** [kazumi3858/payreco-backend#46]
## 環境構築のメモ😆

rails newしました。

```bash
rails _7.0.3.1_ new . -d postgresql --skip-action-cable --skip-action-text --skip-action-mailer --skip-action-mailbox --skip-test --skip-active-storage --api
```

Gemfileに追加。
```ruby
gem 'rack-cors'
gem 'dotenv-rails'

group :development, :test do
  # 省略
  gem 'rspec-rails'
  gem 'factory_bot_rails'
end

group :development do
  # 省略
  gem 'rubocop', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rails', require: false
  gem 'rubocop-rspec', require: false
end
```
`bundle install`しました。

プロジェクトのルートに`.env`と`.rubocop.yml`を作成。
とりあえず`.rubocop.yml`には設定を記述しました。`.env`は必要になった時に書きます。

```yml
## .rubocop.yml
require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - '**/vendor/**/*'
    - config/**/*
    - config.ru
    - db/migrate/*
    - db/schema.rb
    - tmp/**/*
    - bin/**/*

Style/Documentation:
  Enabled: false

Metrics/ClassLength:
  Exclude:
    - test/**/*

Metrics/BlockLength:
  Exclude:
    - spec/**/*
```

Timezoneを設定しました。
```ruby
# config/application.rb
config.time_zone = 'Tokyo'
config.active_record.default_timezone = :local
```

RSpecの設定です。
```
rails g rspec:install
```
```
# .rspecに以下追記
--format documentation
```
FactoryBotの設定です。
```
# spec/rails_helper.rb
RSpec.configure do |config|
  config.include FactoryBot::Syntax::Methods
end
```

モデルとコントローラーの作成は以下のイシューに記録しました。
https://github.com/kazumi3858/payreco-backend/issues/45

corsにNext.jsのURLを設定しました。
```ruby
# config/initializers/cors.rb
origins "http://localhost:3001"
```
